# Generated by Django 6.1 on 2026-08-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0002_item_category_item_name_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('electronics', 'Electronics'), ('book', 'Book'), ('other', 'Other')], max_length=50),
        ),
    ]
